const MSG = {
  SCAN_REQUEST:       'SCAN_REQUEST',
  SCAN_RESULT:        'SCAN_RESULT',
  SCAN_ERROR:         'SCAN_ERROR',
  HIGHLIGHT_ELEMENT:  'HIGHLIGHT_ELEMENT',
  UNHIGHLIGHT_ALL:    'UNHIGHLIGHT_ALL',
  SCROLL_TO_ELEMENT:  'SCROLL_TO_ELEMENT',
  GET_CACHED_RESULTS: 'GET_CACHED_RESULTS',
  PANEL_READY:        'PANEL_READY',
};
